
import adtm.DBConnection;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Desktop
 */
public class ATMMenu extends javax.swing.JFrame {
    int userId;
    String userName;
    
    



    /**
     * Creates new form ATMMENU
     */
  public ATMMenu(int id, String name) {
    userId = id;
    userName = name;

    setTitle("ATM Menu");
    initComponents();
    lblWelcome.setText("Welcome, " + userName);

    setLocationRelativeTo(null); // center the window
    setVisible(true); // ✅ THIS IS CRITICAL if you're not calling .setVisible() externally
}

       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCheck = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnViewHistoryLogs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        btnCheck.setText("Check Balance");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        btnDeposit.setText("Deposit");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        lblWelcome.setText("jLabel1");

        btnViewHistoryLogs.setText("History Logs");
        btnViewHistoryLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHistoryLogsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnViewHistoryLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnViewHistoryLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        try (Connection con = DBConnection.connect()) {
            if (userId == 0) {
                JOptionPane.showMessageDialog(this, "You must log in first.");
                return;
            }

            PreparedStatement ps = con.prepareStatement("SELECT balance FROM accounts WHERE id = ?");
            ps.setInt(1, userId);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                double balance = rs.getDouble("balance");
                JOptionPane.showMessageDialog(this, "Balance: ₱" + balance);
            } else {
                JOptionPane.showMessageDialog(this, "Account not found.");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
       String amtStr = JOptionPane.showInputDialog(this, "Enter deposit amount:");

        if (amtStr == null) {
            JOptionPane.showMessageDialog(this, "Deposit cancelled.");
            return;
        }

        amtStr = amtStr.trim();

        if (amtStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Amount cannot be empty.");
            return;
        }

        try {
            double amount = Double.parseDouble(amtStr);

            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "Amount must be greater than 0.");
                return;
            }

            try (Connection con = DBConnection.connect()) {
                con.setAutoCommit(false); // Optional: Begin transaction

                // 1. Update balance
                PreparedStatement ps1 = con.prepareStatement("UPDATE accounts SET balance = balance + ? WHERE id = ?");
                ps1.setDouble(1, amount);
                ps1.setInt(2, userId);
                ps1.executeUpdate();

                // 2. Insert into history_logs
                PreparedStatement ps2 = con.prepareStatement(
                    "INSERT INTO history_logs (history_acc_id, history_type, history_change_ammount) VALUES (?, ?, ?)"
                );
                ps2.setInt(1, userId);
                ps2.setString(2, "deposit");
                ps2.setDouble(3, amount);
                ps2.executeUpdate();

                con.commit(); // Optional: Commit transaction
                JOptionPane.showMessageDialog(this, "Deposited ₱" + amount);
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a number.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
       String amtStr = JOptionPane.showInputDialog(this, "Enter withdraw amount:");

        if (amtStr == null) {
            JOptionPane.showMessageDialog(this, "Withdrawal cancelled.");
            return;
        }

        amtStr = amtStr.trim();

        if (amtStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Withdrawal amount cannot be empty.");
            return;
        }

        try {
            double amount = Double.parseDouble(amtStr);

            if (amount <= 0) {
                JOptionPane.showMessageDialog(this, "Amount must be greater than 0.");
                return;
            }

            try (Connection con = DBConnection.connect()) {
                con.setAutoCommit(false); // Start transaction

                // 1. Check balance
                PreparedStatement check = con.prepareStatement("SELECT balance FROM accounts WHERE id = ?");
                check.setInt(1, userId);
                ResultSet rs = check.executeQuery();

                if (rs.next()) {
                    double balance = rs.getDouble("balance");

                    if (balance >= amount) {
                        // 2. Perform withdrawal
                        PreparedStatement ps1 = con.prepareStatement("UPDATE accounts SET balance = balance - ? WHERE id = ?");
                        ps1.setDouble(1, amount);
                        ps1.setInt(2, userId);
                        ps1.executeUpdate();

                        // 3. Insert into history_logs
                        PreparedStatement ps2 = con.prepareStatement(
                            "INSERT INTO history_logs (history_acc_id, history_type, history_change_ammount) VALUES (?, ?, ?)"
                        );
                        ps2.setInt(1, userId);
                        ps2.setString(2, "withdraw");
                        ps2.setDouble(3, amount);
                        ps2.executeUpdate();

                        con.commit(); // Commit both changes
                        JOptionPane.showMessageDialog(this, "Successfully withdrew ₱" + amount);
                    } else {
                        JOptionPane.showMessageDialog(this, "Insufficient funds.\nYour current balance is ₱" + balance);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Account not found.");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid input. Please enter a valid number.");
        }


    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
        new ATMLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewHistoryLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHistoryLogsActionPerformed
        try (Connection con = DBConnection.connect()) {
            String query = "SELECT history_id, history_acc_id, history_type, history_change_ammount, history_date FROM history_logs WHERE history_acc_id = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setInt(1, userId); // class field holding current logged-in user's ID

            ResultSet rs = ps.executeQuery();

            String[] columnNames = {"ID", "Type", "Amount", "Date"};
            DefaultTableModel model = new DefaultTableModel(columnNames, 0);

            while (rs.next()) {
                int id = rs.getInt("history_id");
                String type = rs.getString("history_type");
                double amount = rs.getDouble("history_change_ammount");
                String date = rs.getString("history_date");

                model.addRow(new Object[]{id, type, amount, date});
            }

            JTable table = new JTable(model);
            JScrollPane scrollPane = new JScrollPane(table);
            scrollPane.setPreferredSize(new Dimension(600, 300));

            JOptionPane.showMessageDialog(this, scrollPane, "History Logs", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error loading history logs: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnViewHistoryLogsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ATMLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewHistoryLogs;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
